stages:
  Data_Ingestion_from_GCP_Bucket:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/raw/train.csv
      - artifacts/raw/test.csv
    desc: "Extract data from remote API"

  Data_Processing:
    cmd: python src/data_processing.py
    deps:
      - artifacts/raw/train.csv
      - artifacts/raw/test.csv
    outs:
      - artifacts/processed/process_train.csv
      - artifacts/processed/process_test.csv
    desc: "Process raw CSVs"

  Model_Training:
    cmd: python src/model_training.py
    deps:
      - artifacts/processed/process_train.csv
      - artifacts/processed/process_test.csv
    outs:
      - artifacts/models/best_model.pkl
